# Generated by Django 4.0.10 on 2024-11-29 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('feed', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('bedroom_count', models.PositiveIntegerField()),
                ('review_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('usd_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('center', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('amenities', models.JSONField(default=list)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('center', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('state_abbr', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocalizeAccommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('policy', models.JSONField(default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.accommodation')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='localizeaccommodation',
            constraint=models.UniqueConstraint(fields=('property', 'language'), name='unique_localization_per_language'),
        ),
    ]
