# Generated by Django 4.0.10 on 2024-12-02 05:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
