# Generated by Django 4.0.10 on 2024-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_accommodation_bedroom_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
